export const TIME_DISPLAY = {
  ONLY_DAY: 'DD',
  ONLY_MONTH: 'MM',
  ONLY_YEAR: 'YYYY',
  DAY_AND_MONTH: 'DD-MM',
  MONTH_AND_YEAR: 'MM-YYYY',
  BE: 'YYYY-MM-DD',
  BASIC: 'DD/MM/YYYY',
  DOTTED: 'DD.MMM.YYYY HH:mm',
  STRIKETHROUGH: 'DD-MM-YYYY',
  SPACE: 'DD MM YYYY HH:mm',
};

export const TIME_DISPLAY_FORMATS = [
  TIME_DISPLAY.BASIC,
  TIME_DISPLAY.DOTTED,
  TIME_DISPLAY.STRIKETHROUGH,
  TIME_DISPLAY.SPACE,
];
